version: 2
aliases:
  - &node_version node:8.11.3
  # Common steps
  - &restore_npm_cache
    restore_cache:
      name: Restore npm dependencies cache
      key: npm-dependency-{{ checksum "package.json" }}

jobs:
  dependencies:
    docker:
      - image: *node_version
    working_directory: ~/client-matrix-js
    steps:
      - checkout
      - *restore_npm_cache
      - run: npm install
      - save_cache:
          name: Save npm dependencies cache
          key: npm-dependency-{{ checksum "package.json" }}
          paths:
            - ~/client-matrix-js/node_modules

  lint_test:
    docker:
      - image: *node_version
    working_directory: ~/client-matrix-js
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Lint code
          command: npm run lint
          when: always

  unit_test:
    docker:
      - image: *node_version
        environment:
           TZ: "/usr/share/zoneinfo/Europe/London"
    working_directory: ~/client-matrix-js
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Jest tests
          command: npm run test
          when: always

  build_and_publish:
    docker:
      - image: *node_version
        environment:
           TZ: "/usr/share/zoneinfo/Europe/London"
    working_directory: ~/client-matrix-js
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Jest tests
          command: ./build-and-publish.sh
          when: always

workflows:
  version: 2
  datasciencefe:
    jobs:
      - dependencies
      - lint_test:
          requires:
            - dependencies
      - unit_test:
          requires:
            - dependencies
      - build_and_publish:
          requires:
            - lint_test
            - unit_test
          filters:
            branches:
              only:
                - master
